### ISSUE TITLE
BUG for "download our pretrained Model"

### ISSUE THREAD

**Issue by rex131** [renezurbruegg/SemanticInstanceFusion#3]
hi, I am trying to download the pre trained model and I run the 'download_model.py' . but i get an issue :

requests.exceptions.SSLError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1CGXF--IecmGlmmw7lUTTBuPkXQrOXzkv (Caused by SSLError(SSLEOFError(base)

here is the detail:

 python3 download_model.py
Traceback (most recent call last):
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/turtlepc-04/anaconda3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/turtlepc-04/anaconda3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/turtlepc-04/anaconda3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1CGXF--IecmGlmmw7lUTTBuPkXQrOXzkv (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_model.py", line 35, in <module>
    download_file_from_google_drive(file_id, destination)
  File "download_model.py", line 8, in download_file_from_google_drive
    response = session.get(URL, params = { 'id' : id }, stream = True)
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/turtlepc-04/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1CGXF--IecmGlmmw7lUTTBuPkXQrOXzkv (Caused by SSLError(SSLEOFError(base)

what shoudl i do to solve this problem. it will be vrey kind of you if you can reply me. thank you for your time

**Comment by renezurbruegg** [comment]
Hi

I can't reproduce the error on my side.
Can you try downloading the model manually?

https://drive.google.com/file/d/1CGXF--IecmGlmmw7lUTTBuPkXQrOXzkv/view?usp=drivesdk

**Comment by rex131** [comment]
i can downloud it manually, thank you for your time

**Comment by kungsooo** [comment]
> 我可以手动降低音量，感谢您的时间
你好，可以请求一份pretrained Model吗？非常感谢！
